source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
# Use PostgreSQL as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# bootstrap-generators
gem 'bootstrap-generators', '~> 3.1.1'

# Gema para trabajar con archivos
gem "paperclip", "~> 4.2"

# Gemas para ser usadas solo en el ambiente de desarrollo
group :development do

  # Gema para ver descripciones mas claras de los errores en el navegador
  gem "better_errors"

  # Gema que agrega una consola REPL para hacer debug sobre el codigo 
  gem "binding_of_caller"

  # Gema para provee una interfaz para manipular la base de datos mas facilmente
  gem "rails_admin"

  # Gema que añade comentarios automáticamente sobre el código
  gem 'annotate'

  # Gema para callar los logs de assets
  gem 'quiet_assets'
end

# Gema para gestionar la autenticación de usuarios
gem 'devise'

# Gema para gestionar la autorización por roles
gem 'pundit'

gem 'jquery-turbolinks'

# Chosen
gem 'chosen-rails'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

